---
booktitle: Proceedings of the 36th International Conference on Machine Learning
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
shortname: ICML
year: '2019'
volume: 97
start: 2019-06-09
end: 2019-06-15
published: 2019-05-24
url: https://proceedings.mlr.press
author:
  name: PMLR
conference_number: '36'
layout: proceedings
publisher: PMLR
series: Proceedings of Machine Learning Research
issn: 2640-3498
id: ICML2019
month: 0
cycles: false
bibtex_editor: Chaudhuri, Kamalika and Salakhutdinov, Ruslan
editor:
- given: Kamalika
  family: Chaudhuri
- given: Ruslan
  family: Salakhutdinov
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 36th International Conference on Machine Learning
    Held in Long Beach, California, USA on 09-15 June 2019

  Published as Volume 97 by the Proceedings of Machine Learning Research on 24 May 2019.

  Volume Edited by:
    Kamalika Chaudhuri
    Ruslan Salakhutdinov

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: '09--15 Jun'
baseurl: "/v97"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v97
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: International Conference on Machine Learning
  url: 
  location: Long Beach, California, USA
  dates:
  - 2019-06-09
  - 2019-06-10
  - 2019-06-11
  - 2019-06-12
  - 2019-06-13
  - 2019-06-14
  - 2019-06-15
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
